inhibit_all_warnings!

pod 'NSHash', '1.0.1'
pod 'CocoaLumberjack', '2.2.0'
pod 'Typhoon', '3.3.4'
pod 'AFNetworking', '2.6.0'
pod 'EasyMapping', '0.15.3'

target :PonyTests, :exclusive => true do
  pod 'OCMockito', '1.4.0'
end
