platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

pod 'NSHash', '1.0.1'
pod 'CocoaLumberjack', '2.2.0'
pod 'Typhoon', '3.3.4'
pod 'AFNetworking', '2.6.0'
pod 'EasyMapping', '0.15.3'

link_with 'Pony', 'PonyTests'